/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/apps', '<rootDir>/packages', '<rootDir>/tests'],
  testMatch: ['**/*.test.ts', '**/*.spec.ts'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.json',
      },
    ],
  },
  moduleNameMapper: {
    '^@packages/config/(.*)$': '<rootDir>/packages/config/src/$1',
    '^@packages/config$': '<rootDir>/packages/config/src/index.ts',
    '^@packages/logger/(.*)$': '<rootDir>/packages/logger/src/$1',
    '^@packages/logger$': '<rootDir>/packages/logger/src/index.ts',
    '^@packages/errors/(.*)$': '<rootDir>/packages/errors/src/$1',
    '^@packages/errors$': '<rootDir>/packages/errors/src/index.ts',
    '^@packages/http/(.*)$': '<rootDir>/packages/http/src/$1',
    '^@packages/http$': '<rootDir>/packages/http/src/index.ts',
    '^@packages/database/(.*)$': '<rootDir>/packages/database/src/$1',
    '^@packages/database$': '<rootDir>/packages/database/src/index.ts',
    '^@packages/redis/(.*)$': '<rootDir>/packages/redis/src/$1',
    '^@packages/redis$': '<rootDir>/packages/redis/src/index.ts',
    '^@packages/messaging/(.*)$': '<rootDir>/packages/messaging/src/$1',
    '^@packages/messaging$': '<rootDir>/packages/messaging/src/index.ts',
    '^@packages/auth/(.*)$': '<rootDir>/packages/auth/src/$1',
    '^@packages/auth$': '<rootDir>/packages/auth/src/index.ts',
    '^@packages/validation/(.*)$': '<rootDir>/packages/validation/src/$1',
    '^@packages/validation$': '<rootDir>/packages/validation/src/index.ts',
    '^@packages/types/(.*)$': '<rootDir>/packages/types/src/$1',
    '^@packages/types$': '<rootDir>/packages/types/src/index.ts',
    '^@packages/observability/(.*)$': '<rootDir>/packages/observability/src/$1',
    '^@packages/observability$': '<rootDir>/packages/observability/src/index.ts',
    '^@packages/calculators/(.*)$': '<rootDir>/packages/calculators/src/$1',
    '^@packages/calculators$': '<rootDir>/packages/calculators/src/index.ts',
    '^@packages/budgeting/(.*)$': '<rootDir>/packages/budgeting/src/$1',
    '^@packages/budgeting$': '<rootDir>/packages/budgeting/src/index.ts',
    '^@packages/investments/(.*)$': '<rootDir>/packages/investments/src/$1',
    '^@packages/investments$': '<rootDir>/packages/investments/src/index.ts',
    '^@packages/analytics/(.*)$': '<rootDir>/packages/analytics/src/$1',
    '^@packages/analytics$': '<rootDir>/packages/analytics/src/index.ts',
    '^@apps/identity-service/(.*)$': '<rootDir>/apps/identity-service/src/$1',
    '^@apps/identity-service$': '<rootDir>/apps/identity-service/src/index.ts',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'apps/**/*.ts',
    'packages/**/*.ts',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/dist/**',
  ],
};

export default config;
